# Generated by Django 3.2.6 on 2021-08-19 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Marka')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endurance', models.IntegerField(choices=[(4, 4), (8, 8), (5, 5), (7, 7), (9, 9), (1, 1), (10, 10), (3, 3), (2, 2), (6, 6)], verbose_name='Wytrzymałość')),
                ('leading', models.IntegerField(choices=[(4, 4), (8, 8), (5, 5), (7, 7), (9, 9), (1, 1), (10, 10), (3, 3), (2, 2), (6, 6)], verbose_name='Prowadzenie')),
                ('operating_cost', models.IntegerField(choices=[(4, 4), (8, 8), (5, 5), (7, 7), (9, 9), (1, 1), (10, 10), (3, 3), (2, 2), (6, 6)], verbose_name='Koszty eksploatacji')),
                ('design', models.IntegerField(choices=[(4, 4), (8, 8), (5, 5), (7, 7), (9, 9), (1, 1), (10, 10), (3, 3), (2, 2), (6, 6)], verbose_name='Wygląd')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=32, verbose_name='Model')),
                ('versions', models.CharField(max_length=32, verbose_name='Wersja')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rate_a_car_app.brand', verbose_name='Marka')),
                ('rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rate_a_car_app.rate', verbose_name='Ocena')),
            ],
        ),
    ]
