# Generated by Django 3.2.6 on 2021-08-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_a_car_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year_of_production',
            field=models.CharField(max_length=12, null=True, verbose_name='Lata produkcji'),
        ),
    ]
