# Generated by Django 3.2.6 on 2021-08-19 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate_a_car_app', '0002_car_year_of_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rate_a_car_app.brand', unique=True, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(max_length=32, unique=True, verbose_name='Model'),
        ),
    ]
