# Generated by Django 3.2.6 on 2021-08-19 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate_a_car_app', '0003_auto_20210819_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rate_a_car_app.brand', verbose_name='Marka'),
        ),
    ]
