# Generated by Django 3.2.6 on 2021-08-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_a_car_app', '0004_alter_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(max_length=32, verbose_name='Model'),
        ),
    ]
